#spring:
  application:
    name: springboot
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  'jdbc:mysql://rm-bp17vsrx0enq7yj01ao.mysql.rds.aliyuncs.com/user_center'
    username: user
    password: Hqh55555
    #session 失效时间
  session:
    timeout: 86400
service:
  address: 0.0.0.0

